### ISSUE TITLE
Some problems with webpack

### ISSUE THREAD

**Issue by VladimirCores** [ManuelDeLeon/viewmodel-react-starter#2]
This is what i have after cloning, npm install and npm start

> viewmodel-react-starter@1.0.0 start /home/dqvsra/Documents/Products/ViewModel/viewmodel-react-starter
> node server.js

Listening at http://localhost:3000/
Hash: 59eaceee15f587a76e03
Version: webpack 1.14.0
Time: 2586ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.21 MB       0  [emitted]  main
chunk    {0} bundle.js (main) 1.07 MB [rendered]
    [0] multi main 52 bytes {0} [built]
    [1] (webpack)-dev-server/client?http://localhost:3000 3.97 kB {0} [built]
. 
.
.

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /home/dqvsra/Documents/Products/ViewModel/viewmodel-react-starter/src
 @ ./src/index.js 1:364-395

ERROR in ./src/App.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /home/dqvsra/Documents/Products/ViewModel/viewmodel-react-starter/src
 @ ./src/App.js 1:364-395

ERROR in ./src/Person/Person.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /home/dqvsra/Documents/Products/ViewModel/viewmodel-react-starter/src/Person
 @ ./src/Person/Person.js 1:364-395
webpack: bundle is now VALID.

**Comment by ManuelDeLeon** [comment]
That starter is based on Gaeron's React boilerplate which is ancient. It should work if you update `react-hot-loader`: 
`npm install --save-dev react-hot-loader@latest`

Check out this thread for more info: http://stackoverflow.com/questions/40652327/module-not-found-error-cannot-resolve-module-react-lib-reactmount

Remember that you can use any React boilerplate/starter and add ViewModel to it so you have plenty of options =)

**Comment by ManuelDeLeon** [comment]
btw, I just updated package.json to use react-hot-loade 1.3.1

**Comment by VladimirCores** [comment]
Did you tried to run it by yourself, starting from clean folder?

**Comment by ManuelDeLeon** [comment]
Yes.
```
git clone https://github.com/ManuelDeLeon/viewmodel-react-starter.git
cd viewmodel-react-starter
npm i
npm start
```
All's good.
